#include "Material.h"

namespace Derpy { namespace Graphics {

	enum class MaterialType{
		SOLID,
		SOLID_2_LAYER,
		LIGHTMAP,
		LIGHTMAP_ADD,
		LIGHTMAP_M2,
		LIGHTMAP_M4,
		LIGHTMAP_LIGHTING,
		LIGHTMAP_LIGHTING_M2,
		LIGHTMAP_LIGHTING_M4,
		DETAIL_MAP,
		SPHERE_MAP,
		REFLECTION_2_LAYER,
		TRANSPARENT_ADD_COLOR,
		TRANSPARENT_ALPHA_CHANNEL,
		TRANSPARENT_ALPHA_CHANNEL_REF,
		TRANSPARENT_VERTEX_ALPHA,
		TRANSPARENT_REFLECTION_2_LAYER,
		NORMAL_MAP_SOLID,
		NORMAL_MAP_TRANSPARENT_ADD_COLOR,
		NORMAL_MAP_TRANSPARENT_VERTEX_ALPHA,
		PARALLAX_MAP_SOLID,
		PARALLAX_MAP_TRANSPARENT_ADD_COLOR,
		PARALLAX_MAP_TRANSPARENT_VERTEX_ALPHA,
		ONETEXTURE_BLEND,
		FORCE_32BIT = 0x7fffffff
	};


} }